Feature/initial qbittorrent rebranding (#1)
* Update: Initial cleanup

* First passing prototype

* Added: qBt categories

* significant progress

* more upgrades

* last set of updates before success run

* One step closer to a release

* 0.0.1 ready now

* Bugfix: ansible-lint workflow

* Adjusting symlink for workflow

* Bugfix: ansible-lint try 2

* Bugfix: ansible-lint try #3

diff --git a/templates/autobrr/upgrade_autobrr.sh.j2 b/templates/autobrr/upgrade_autobrr.sh.j2
--- a/templates/autobrr/upgrade_autobrr.sh.j2
+++ b/templates/autobrr/upgrade_autobrr.sh.j2
@@ -5,16 +5,24 @@
 export AUTOBRR_VERSION="{{ autobrr_ver }}"
 ##############################################
 
+# Check if required commands are installed
+for cmd in curl tar; do
+  if ! command -v "$cmd" >/dev/null 2>&1; then
+    echo "Error: $cmd is not installed." >&2
+    exit 1
+  fi
+done
+
 echo "Downloading & unpacking a new version of Autobrr..."
 cd
-wget https://github.com/autobrr/autobrr/releases/download/v${AUTOBRR_VERSION}/autobrr_${AUTOBRR_VERSION}_linux_x86_64.tar.gz
-tar xvzf autobrr_${AUTOBRR_VERSION}_linux_x86_64.tar.gz
+/usr/bin/curl -LO https://github.com/autobrr/autobrr/releases/download/v${AUTOBRR_VERSION}/autobrr_${AUTOBRR_VERSION}_linux_x86_64.tar.gz
+/usr/bin/tar xvzf autobrr_${AUTOBRR_VERSION}_linux_x86_64.tar.gz
 
 echo "Stopping Autobrr service..."
-sudo systemctl stop autobrr@{{ ansible_user }}.service
+sudo /usr/bin/systemctl stop autobrr@{{ ansible_user }}.service
 
 echo "Upgrading the Autobrr binaries..."
-sudo mv -v autobrr autobrrctl /usr/local/bin/
+sudo /usr/bin/mv -v autobrr autobrrctl /usr/local/bin/
 
 echo "Restoring default SELinux security contexts..."
 sudo /usr/sbin/restorecon -Rv /usr/local/bin/
@@ -32,11 +40,11 @@ cd /home/{{ ansible_user }}/.config/autobrr/filters && /usr/local/bin/autobrrctl
 
 echo "Backing up..."
 cd
-tar cvzf autobrr_backup_$(date +%Y-%m-%d_%H%M%S).tgz /home/{{ ansible_user }}/.config/autobrr
+/usr/bin/tar cvzf autobrr_backup_$(date +%Y-%m-%d_%H%M%S).tgz /home/{{ ansible_user }}/.config/autobrr
 
 echo "Starting the Autobrr service again..."
-sudo systemctl start autobrr@{{ ansible_user }}.service
-sudo systemctl is-active autobrr@{{ ansible_user }}.service
+sudo /usr/bin/systemctl start autobrr@{{ ansible_user }}.service
+sudo /usr/bin/systemctl is-active autobrr@{{ ansible_user }}.service
 
 echo "Cleanup..."
 rm -vf autobrr_${AUTOBRR_VERSION}_linux_x86_64.tar.gz LICENSE README.md
